"""Generate a conftest.py scaffold for running TestWeaver-generated
pytest files against an arbitrary target FastAPI project.

Context: tests/conftest.py in this repo only wires up the `client`
fixture for TestWeaver's own internal demo_app fixture, used to
validate the generator itself. It intentionally does not try to run
against arbitrary user projects — that requires knowing the target
app's import path, which this module lets you scaffold.

`generate_conftest()` writes a conftest.py into the target project
that provides the same `client` fixture signature every generated
test expects (see templates/test_case.py.j2), pointed at the given
app. The `reset_state` fixture is left as a TODO for the user to
fill in, since TestWeaver has no generic way to know how to reset a
project's own storage between tests.

Known limitation (tracked separately, not solved by this module):
case_generator's build_path_params() currently assigns the same path
param value (e.g. book_id=1) to both a "resource exists" case and a
"resource not found" case for the same feature. No reset_state
implementation can satisfy both simultaneously — that needs a fix in
case_generator/payload.py, not here.
"""

from __future__ import annotations

from pathlib import Path

_CONFTEST_TEMPLATE = '''"""Auto-generated by TestWeaver (scaffold).

Wires up the `client` fixture every TestWeaver-generated test expects
(see src/testweaver/templates/test_case.py.j2). Regenerate this file
if the target app path changes, rather than hand-editing the import.

Target app: {app_import}
"""
from collections.abc import Iterator

import pytest
from fastapi.testclient import TestClient

from {app_module} import {app_attr} as app


@pytest.fixture(scope="function", autouse=True)
def reset_state() -> None:
    """Runs before every generated test.

    TODO: fill in with whatever this project needs to reset to a
    known state before each test (e.g. clear an in-memory dict,
    reset a test DB session, re-seed fixture rows). Left as a no-op
    here because TestWeaver cannot generically infer your storage
    layer.

    Known limitation: if the matrix has both a "resource exists" case
    and a "resource not found" case that resolve to the same path
    param, no single reset can satisfy both — see case_generator's
    build_path_params().
    """


@pytest.fixture(scope="function")
def client() -> Iterator[TestClient]:
    with TestClient(app) as test_client:
        yield test_client
'''


def generate_conftest(app_import: str, output_path: Path) -> Path:
    """Write a conftest.py scaffold pointed at `app_import`.

    app_import: "module.path:attr", e.g. "main:app" or "src.main:app".
    Raises ValueError if app_import isn't in that form.
    """
    module_path, sep, attr = app_import.rpartition(":")
    if not sep or not module_path or not attr:
        raise ValueError(
            f"app_import must look like 'module.path:attr', got {app_import!r}"
        )
    content = _CONFTEST_TEMPLATE.format(
        app_import=app_import, app_module=module_path, app_attr=attr
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path