[project]
name = "testweaver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "wchng", email = "jwcgomunamu@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.140.13",
    "jinja2>=3.1.6",
    "rich>=15.0.0",
    "typer>=0.27.0",
]

[project.scripts]
testweaver = "testweaver:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.0",
]
